source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RumbleStrip_Example', :exclusive => true do
  pod "RumbleStrip", :path => "../"
end

target 'RumbleStrip_Tests', :exclusive => true do
  pod "RumbleStrip", :path => "../"

  
end
